parameters:
    fidesio_isidore.client.url: http://seth.lan/ligueparis/trunk/web/ligueparis_isidore/
    fidesio_isidore.client.login: apiligueparis
    fidesio_isidore.client.password: apiLigueP@r!s
