parameters:
    fidesio_isidore.client.url: http://fidesio:fidesio@ligueparis.isidore.staging.fides.io/
    fidesio_isidore.client.login: apiligueparis
    fidesio_isidore.client.password: apiLigueP@r!s
